#!/usr/bin/env bash

: ${GCLOUD_SRC_PATH=${PWD}}

docker run --rm -it --workdir=/home/user/src \
	-v ~/.config/gcloud:/home/user/.config/gcloud \
	-v $GCLOUD_SRC_PATH:/home/user/src:ro \
	asssaf/gcloud-sdk-python \
	gcloud $*
